/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Author,
  AuthorCreate,
  HTTPValidationError,
} from '../models/index';
import {
    AuthorFromJSON,
    AuthorToJSON,
    AuthorCreateFromJSON,
    AuthorCreateToJSON,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
} from '../models/index';

export interface CreateAuthorApiV1AuthorsCreatePostRequest {
    authorCreate: AuthorCreate;
}

/**
 * 
 */
export class AuthorsApi extends runtime.BaseAPI {

    /**
     * Create Author
     */
    async createAuthorApiV1AuthorsCreatePostRaw(requestParameters: CreateAuthorApiV1AuthorsCreatePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Author>> {
        if (requestParameters['authorCreate'] == null) {
            throw new runtime.RequiredError(
                'authorCreate',
                'Required parameter "authorCreate" was null or undefined when calling createAuthorApiV1AuthorsCreatePost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/v1/authors/create`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AuthorCreateToJSON(requestParameters['authorCreate']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AuthorFromJSON(jsonValue));
    }

    /**
     * Create Author
     */
    async createAuthorApiV1AuthorsCreatePost(requestParameters: CreateAuthorApiV1AuthorsCreatePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Author> {
        const response = await this.createAuthorApiV1AuthorsCreatePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get All Authors
     */
    async getAllAuthorsApiV1AuthorsGetAllGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Author>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/authors/getAll`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(AuthorFromJSON));
    }

    /**
     * Get All Authors
     */
    async getAllAuthorsApiV1AuthorsGetAllGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Author>> {
        const response = await this.getAllAuthorsApiV1AuthorsGetAllGetRaw(initOverrides);
        return await response.value();
    }

}
