/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Author,
} from '../models/index';
import {
    AuthorFromJSON,
    AuthorToJSON,
} from '../models/index';

/**
 * 
 */
export class AuthorsApi extends runtime.BaseAPI {

    /**
     * Get All Authors
     */
    async getAllAuthorsApiV1AuthorsGetAllGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Author>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/authors/getAll`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(AuthorFromJSON));
    }

    /**
     * Get All Authors
     */
    async getAllAuthorsApiV1AuthorsGetAllGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Author>> {
        const response = await this.getAllAuthorsApiV1AuthorsGetAllGetRaw(initOverrides);
        return await response.value();
    }

}
