/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type Author,
    AuthorFromJSON,
    AuthorToJSON,
} from '../models/Author';
import {
    type AuthorCreate,
    AuthorCreateFromJSON,
    AuthorCreateToJSON,
} from '../models/AuthorCreate';
import {
    type HTTPValidationError,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
} from '../models/HTTPValidationError';

export interface CreateAuthorApiV1AuthorsCreatePostRequest {
    /**
     *
     */
    authorCreate: AuthorCreate;
}

export interface GetAllAuthorsApiV1AuthorsGetAllGetRequest {
    /**
     *
     */
    skip?: number;
    /**
     *
     */
    limit?: number;
}

export interface GetAuthorApiV1AuthorsAuthorIdGetRequest {
    /**
     *
     */
    authorId: number;
}

/**
 *
 */
export class AuthorsApi extends runtime.BaseAPI {

    /**
     * Creates request options for createAuthorApiV1AuthorsCreatePost without sending the request
     */
    async createAuthorApiV1AuthorsCreatePostRequestOpts(requestParameters: CreateAuthorApiV1AuthorsCreatePostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['authorCreate'] == null) {
            throw new runtime.RequiredError(
                'authorCreate',
                'Required parameter "authorCreate" was null or undefined when calling createAuthorApiV1AuthorsCreatePost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/authors/create`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AuthorCreateToJSON(requestParameters['authorCreate']),
        };
    }

    /**
     * Create Author
     */
    async createAuthorApiV1AuthorsCreatePostRaw(requestParameters: CreateAuthorApiV1AuthorsCreatePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Author>> {
        const requestOptions = await this.createAuthorApiV1AuthorsCreatePostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AuthorFromJSON(jsonValue));
    }

    /**
     * Create Author
     */
    async createAuthorApiV1AuthorsCreatePost(requestParameters: CreateAuthorApiV1AuthorsCreatePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Author> {
        const response = await this.createAuthorApiV1AuthorsCreatePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getAllAuthorsApiV1AuthorsGetAllGet without sending the request
     */
    async getAllAuthorsApiV1AuthorsGetAllGetRequestOpts(requestParameters: GetAllAuthorsApiV1AuthorsGetAllGetRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['skip'] != null) {
            queryParameters['skip'] = requestParameters['skip'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/authors/getAll`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get All Authors
     */
    async getAllAuthorsApiV1AuthorsGetAllGetRaw(requestParameters: GetAllAuthorsApiV1AuthorsGetAllGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Author>>> {
        const requestOptions = await this.getAllAuthorsApiV1AuthorsGetAllGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(AuthorFromJSON));
    }

    /**
     * Get All Authors
     */
    async getAllAuthorsApiV1AuthorsGetAllGet(requestParameters: GetAllAuthorsApiV1AuthorsGetAllGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Author>> {
        const response = await this.getAllAuthorsApiV1AuthorsGetAllGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getAuthorApiV1AuthorsAuthorIdGet without sending the request
     */
    async getAuthorApiV1AuthorsAuthorIdGetRequestOpts(requestParameters: GetAuthorApiV1AuthorsAuthorIdGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['authorId'] == null) {
            throw new runtime.RequiredError(
                'authorId',
                'Required parameter "authorId" was null or undefined when calling getAuthorApiV1AuthorsAuthorIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/authors/{author_id}`;
        urlPath = urlPath.replace('{author_id}', encodeURIComponent(String(requestParameters['authorId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get Author
     */
    async getAuthorApiV1AuthorsAuthorIdGetRaw(requestParameters: GetAuthorApiV1AuthorsAuthorIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Author>> {
        const requestOptions = await this.getAuthorApiV1AuthorsAuthorIdGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AuthorFromJSON(jsonValue));
    }

    /**
     * Get Author
     */
    async getAuthorApiV1AuthorsAuthorIdGet(requestParameters: GetAuthorApiV1AuthorsAuthorIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Author> {
        const response = await this.getAuthorApiV1AuthorsAuthorIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
