/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type HTTPValidationError,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
} from '../models/HTTPValidationError';

export interface ImportDatabaseApiV1DatabaseImportPostRequest {
    /**
     *
     */
    file: Blob;
}

/**
 *
 */
export class DatabaseApi extends runtime.BaseAPI {

    /**
     * Creates request options for exportDatabaseApiV1DatabaseExportGet without sending the request
     */
    async exportDatabaseApiV1DatabaseExportGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v1/database/export`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Export the database and images as a ZIP file.  Requires an authenticated admin user. Both reading the live database file (which contains user password hashes) and downloading every stored image are inherently privileged operations.  Returns:     Response: A ZIP file containing the database and images.     The response will have the following headers:     - Content-Type: application/zip     - Content-Disposition: attachment; filename=\"mangadb_export.zip\"
     * Export Database
     */
    async exportDatabaseApiV1DatabaseExportGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.exportDatabaseApiV1DatabaseExportGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Export the database and images as a ZIP file.  Requires an authenticated admin user. Both reading the live database file (which contains user password hashes) and downloading every stored image are inherently privileged operations.  Returns:     Response: A ZIP file containing the database and images.     The response will have the following headers:     - Content-Type: application/zip     - Content-Disposition: attachment; filename=\"mangadb_export.zip\"
     * Export Database
     */
    async exportDatabaseApiV1DatabaseExportGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.exportDatabaseApiV1DatabaseExportGetRaw(initOverrides);
    }

    /**
     * Creates request options for importDatabaseApiV1DatabaseImportPost without sending the request
     */
    async importDatabaseApiV1DatabaseImportPostRequestOpts(requestParameters: ImportDatabaseApiV1DatabaseImportPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['file'] == null) {
            throw new runtime.RequiredError(
                'file',
                'Required parameter "file" was null or undefined when calling importDatabaseApiV1DatabaseImportPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }

        const consumes: runtime.Consume[] = [
            { contentType: 'multipart/form-data' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        // use FormData to transmit files using content-type "multipart/form-data"
        useForm = canConsumeForm;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['file'] != null) {
            formParams.append('file', requestParameters['file'] as any);
        }


        let urlPath = `/api/v1/database/import`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        };
    }

    /**
     * Import a database and images from a ZIP file. Requires an authenticated admin user. The handler rejects uploads that are not valid ZIP archives, exceed :data:`MAX_IMPORT_BYTES`, or contain entries whose resolved paths fall outside the extraction directory (zip-slip protection).
     * Import Database
     */
    async importDatabaseApiV1DatabaseImportPostRaw(requestParameters: ImportDatabaseApiV1DatabaseImportPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const requestOptions = await this.importDatabaseApiV1DatabaseImportPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Import a database and images from a ZIP file. Requires an authenticated admin user. The handler rejects uploads that are not valid ZIP archives, exceed :data:`MAX_IMPORT_BYTES`, or contain entries whose resolved paths fall outside the extraction directory (zip-slip protection).
     * Import Database
     */
    async importDatabaseApiV1DatabaseImportPost(requestParameters: ImportDatabaseApiV1DatabaseImportPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.importDatabaseApiV1DatabaseImportPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
