/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  HTTPValidationError,
} from '../models/index';
import {
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
} from '../models/index';

export interface ImportDatabaseApiV1DatabaseImportPostRequest {
    file: Blob;
}

/**
 * 
 */
export class DatabaseApi extends runtime.BaseAPI {

    /**
     * Export the database and images as a ZIP file.  Returns:     FileResponse: A ZIP file containing the database and images.     The response will have the following headers:     - Content-Type: application/zip     - Content-Disposition: attachment; filename=\"mangadb_export.zip\"
     * Export Database
     */
    async exportDatabaseApiV1DatabaseExportGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/database/export`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Export the database and images as a ZIP file.  Returns:     FileResponse: A ZIP file containing the database and images.     The response will have the following headers:     - Content-Type: application/zip     - Content-Disposition: attachment; filename=\"mangadb_export.zip\"
     * Export Database
     */
    async exportDatabaseApiV1DatabaseExportGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.exportDatabaseApiV1DatabaseExportGetRaw(initOverrides);
    }

    /**
     * Import a database and images from a ZIP file
     * Import Database
     */
    async importDatabaseApiV1DatabaseImportPostRaw(requestParameters: ImportDatabaseApiV1DatabaseImportPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['file'] == null) {
            throw new runtime.RequiredError(
                'file',
                'Required parameter "file" was null or undefined when calling importDatabaseApiV1DatabaseImportPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const consumes: runtime.Consume[] = [
            { contentType: 'multipart/form-data' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        // use FormData to transmit files using content-type "multipart/form-data"
        useForm = canConsumeForm;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['file'] != null) {
            formParams.append('file', requestParameters['file'] as any);
        }

        const response = await this.request({
            path: `/api/v1/database/import`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Import a database and images from a ZIP file
     * Import Database
     */
    async importDatabaseApiV1DatabaseImportPost(requestParameters: ImportDatabaseApiV1DatabaseImportPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.importDatabaseApiV1DatabaseImportPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
