/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type Genre,
    GenreFromJSON,
    GenreToJSON,
} from '../models/Genre';
import {
    type GenreCreate,
    GenreCreateFromJSON,
    GenreCreateToJSON,
} from '../models/GenreCreate';
import {
    type HTTPValidationError,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
} from '../models/HTTPValidationError';

export interface CreateGenreApiV1GenresCreatePostRequest {
    /**
     *
     */
    genreCreate: GenreCreate;
}

export interface GetAllGenresApiV1GenresGetAllGetRequest {
    /**
     *
     */
    skip?: number;
    /**
     *
     */
    limit?: number;
}

export interface GetGenreApiV1GenresGenreIdGetRequest {
    /**
     *
     */
    genreId: number;
}

/**
 *
 */
export class GenresApi extends runtime.BaseAPI {

    /**
     * Creates request options for createGenreApiV1GenresCreatePost without sending the request
     */
    async createGenreApiV1GenresCreatePostRequestOpts(requestParameters: CreateGenreApiV1GenresCreatePostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['genreCreate'] == null) {
            throw new runtime.RequiredError(
                'genreCreate',
                'Required parameter "genreCreate" was null or undefined when calling createGenreApiV1GenresCreatePost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/genres/create`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: GenreCreateToJSON(requestParameters['genreCreate']),
        };
    }

    /**
     * Create Genre
     */
    async createGenreApiV1GenresCreatePostRaw(requestParameters: CreateGenreApiV1GenresCreatePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Genre>> {
        const requestOptions = await this.createGenreApiV1GenresCreatePostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GenreFromJSON(jsonValue));
    }

    /**
     * Create Genre
     */
    async createGenreApiV1GenresCreatePost(requestParameters: CreateGenreApiV1GenresCreatePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Genre> {
        const response = await this.createGenreApiV1GenresCreatePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getAllGenresApiV1GenresGetAllGet without sending the request
     */
    async getAllGenresApiV1GenresGetAllGetRequestOpts(requestParameters: GetAllGenresApiV1GenresGetAllGetRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['skip'] != null) {
            queryParameters['skip'] = requestParameters['skip'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/genres/getAll`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get All Genres
     */
    async getAllGenresApiV1GenresGetAllGetRaw(requestParameters: GetAllGenresApiV1GenresGetAllGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Genre>>> {
        const requestOptions = await this.getAllGenresApiV1GenresGetAllGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(GenreFromJSON));
    }

    /**
     * Get All Genres
     */
    async getAllGenresApiV1GenresGetAllGet(requestParameters: GetAllGenresApiV1GenresGetAllGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Genre>> {
        const response = await this.getAllGenresApiV1GenresGetAllGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getGenreApiV1GenresGenreIdGet without sending the request
     */
    async getGenreApiV1GenresGenreIdGetRequestOpts(requestParameters: GetGenreApiV1GenresGenreIdGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['genreId'] == null) {
            throw new runtime.RequiredError(
                'genreId',
                'Required parameter "genreId" was null or undefined when calling getGenreApiV1GenresGenreIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/genres/{genre_id}`;
        urlPath = urlPath.replace('{genre_id}', encodeURIComponent(String(requestParameters['genreId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get Genre
     */
    async getGenreApiV1GenresGenreIdGetRaw(requestParameters: GetGenreApiV1GenresGenreIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Genre>> {
        const requestOptions = await this.getGenreApiV1GenresGenreIdGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GenreFromJSON(jsonValue));
    }

    /**
     * Get Genre
     */
    async getGenreApiV1GenresGenreIdGet(requestParameters: GetGenreApiV1GenresGenreIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Genre> {
        const response = await this.getGenreApiV1GenresGenreIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
