/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Genre,
} from '../models/index';
import {
    GenreFromJSON,
    GenreToJSON,
} from '../models/index';

/**
 * 
 */
export class GenresApi extends runtime.BaseAPI {

    /**
     * Get All Genres
     */
    async getAllGenresApiV1GenresGetAllGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Genre>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/genres/getAll`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(GenreFromJSON));
    }

    /**
     * Get All Genres
     */
    async getAllGenresApiV1GenresGetAllGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Genre>> {
        const response = await this.getAllGenresApiV1GenresGetAllGetRaw(initOverrides);
        return await response.value();
    }

}
