/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type HTTPValidationError,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
} from '../models/HTTPValidationError';
import {
    type ListCreate,
    ListCreateFromJSON,
    ListCreateToJSON,
} from '../models/ListCreate';
import {
    type ListModel,
    ListModelFromJSON,
    ListModelToJSON,
} from '../models/ListModel';

export interface CreateListApiV1ListsCreatePostRequest {
    /**
     *
     */
    listCreate: ListCreate;
}

export interface DeleteListApiV1ListsListIdDeleteRequest {
    /**
     *
     */
    listId: number;
}

export interface GetListApiV1ListsListIdGetRequest {
    /**
     *
     */
    listId: number;
}

export interface UpdateListApiV1ListsListIdPutRequest {
    /**
     *
     */
    listId: number;
    /**
     *
     */
    listCreate: ListCreate;
}

/**
 *
 */
export class ListsApi extends runtime.BaseAPI {

    /**
     * Creates request options for createListApiV1ListsCreatePost without sending the request
     */
    async createListApiV1ListsCreatePostRequestOpts(requestParameters: CreateListApiV1ListsCreatePostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['listCreate'] == null) {
            throw new runtime.RequiredError(
                'listCreate',
                'Required parameter "listCreate" was null or undefined when calling createListApiV1ListsCreatePost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/lists/create`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ListCreateToJSON(requestParameters['listCreate']),
        };
    }

    /**
     * Create List
     */
    async createListApiV1ListsCreatePostRaw(requestParameters: CreateListApiV1ListsCreatePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListModel>> {
        const requestOptions = await this.createListApiV1ListsCreatePostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListModelFromJSON(jsonValue));
    }

    /**
     * Create List
     */
    async createListApiV1ListsCreatePost(requestParameters: CreateListApiV1ListsCreatePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListModel> {
        const response = await this.createListApiV1ListsCreatePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deleteListApiV1ListsListIdDelete without sending the request
     */
    async deleteListApiV1ListsListIdDeleteRequestOpts(requestParameters: DeleteListApiV1ListsListIdDeleteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['listId'] == null) {
            throw new runtime.RequiredError(
                'listId',
                'Required parameter "listId" was null or undefined when calling deleteListApiV1ListsListIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/lists/{list_id}`;
        urlPath = urlPath.replace('{list_id}', encodeURIComponent(String(requestParameters['listId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Delete List
     */
    async deleteListApiV1ListsListIdDeleteRaw(requestParameters: DeleteListApiV1ListsListIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListModel>> {
        const requestOptions = await this.deleteListApiV1ListsListIdDeleteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListModelFromJSON(jsonValue));
    }

    /**
     * Delete List
     */
    async deleteListApiV1ListsListIdDelete(requestParameters: DeleteListApiV1ListsListIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListModel> {
        const response = await this.deleteListApiV1ListsListIdDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getListApiV1ListsListIdGet without sending the request
     */
    async getListApiV1ListsListIdGetRequestOpts(requestParameters: GetListApiV1ListsListIdGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['listId'] == null) {
            throw new runtime.RequiredError(
                'listId',
                'Required parameter "listId" was null or undefined when calling getListApiV1ListsListIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/lists/{list_id}`;
        urlPath = urlPath.replace('{list_id}', encodeURIComponent(String(requestParameters['listId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get List
     */
    async getListApiV1ListsListIdGetRaw(requestParameters: GetListApiV1ListsListIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListModel>> {
        const requestOptions = await this.getListApiV1ListsListIdGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListModelFromJSON(jsonValue));
    }

    /**
     * Get List
     */
    async getListApiV1ListsListIdGet(requestParameters: GetListApiV1ListsListIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListModel> {
        const response = await this.getListApiV1ListsListIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getListsApiV1ListsGetAllGet without sending the request
     */
    async getListsApiV1ListsGetAllGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/lists/getAll`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get Lists
     */
    async getListsApiV1ListsGetAllGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ListModel>>> {
        const requestOptions = await this.getListsApiV1ListsGetAllGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ListModelFromJSON));
    }

    /**
     * Get Lists
     */
    async getListsApiV1ListsGetAllGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ListModel>> {
        const response = await this.getListsApiV1ListsGetAllGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getListsWithCountApiV1ListsGetAllWithCountGet without sending the request
     */
    async getListsWithCountApiV1ListsGetAllWithCountGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/lists/getAll/withCount`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get Lists With Count
     */
    async getListsWithCountApiV1ListsGetAllWithCountGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<{ [key: string]: any | null; }>>> {
        const requestOptions = await this.getListsWithCountApiV1ListsGetAllWithCountGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Get Lists With Count
     */
    async getListsWithCountApiV1ListsGetAllWithCountGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<{ [key: string]: any | null; }>> {
        const response = await this.getListsWithCountApiV1ListsGetAllWithCountGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateListApiV1ListsListIdPut without sending the request
     */
    async updateListApiV1ListsListIdPutRequestOpts(requestParameters: UpdateListApiV1ListsListIdPutRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['listId'] == null) {
            throw new runtime.RequiredError(
                'listId',
                'Required parameter "listId" was null or undefined when calling updateListApiV1ListsListIdPut().'
            );
        }

        if (requestParameters['listCreate'] == null) {
            throw new runtime.RequiredError(
                'listCreate',
                'Required parameter "listCreate" was null or undefined when calling updateListApiV1ListsListIdPut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/lists/{list_id}`;
        urlPath = urlPath.replace('{list_id}', encodeURIComponent(String(requestParameters['listId'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: ListCreateToJSON(requestParameters['listCreate']),
        };
    }

    /**
     * Update List
     */
    async updateListApiV1ListsListIdPutRaw(requestParameters: UpdateListApiV1ListsListIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListModel>> {
        const requestOptions = await this.updateListApiV1ListsListIdPutRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListModelFromJSON(jsonValue));
    }

    /**
     * Update List
     */
    async updateListApiV1ListsListIdPut(requestParameters: UpdateListApiV1ListsListIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListModel> {
        const response = await this.updateListApiV1ListsListIdPutRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
