/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  HTTPValidationError,
  ListCreate,
  ListModel,
} from '../models/index';
import {
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    ListCreateFromJSON,
    ListCreateToJSON,
    ListModelFromJSON,
    ListModelToJSON,
} from '../models/index';

export interface CreateListApiV1ListsCreatePostRequest {
    listCreate: ListCreate;
}

/**
 * 
 */
export class ListsApi extends runtime.BaseAPI {

    /**
     * Create List
     */
    async createListApiV1ListsCreatePostRaw(requestParameters: CreateListApiV1ListsCreatePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListModel>> {
        if (requestParameters['listCreate'] == null) {
            throw new runtime.RequiredError(
                'listCreate',
                'Required parameter "listCreate" was null or undefined when calling createListApiV1ListsCreatePost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/v1/lists/create`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ListCreateToJSON(requestParameters['listCreate']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListModelFromJSON(jsonValue));
    }

    /**
     * Create List
     */
    async createListApiV1ListsCreatePost(requestParameters: CreateListApiV1ListsCreatePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListModel> {
        const response = await this.createListApiV1ListsCreatePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get Lists
     */
    async getListsApiV1ListsGetAllGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ListModel>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/lists/getAll`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ListModelFromJSON));
    }

    /**
     * Get Lists
     */
    async getListsApiV1ListsGetAllGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ListModel>> {
        const response = await this.getListsApiV1ListsGetAllGetRaw(initOverrides);
        return await response.value();
    }

}
