/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type HTTPValidationError,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
} from '../models/HTTPValidationError';
import {
    type Manga,
    MangaFromJSON,
    MangaToJSON,
} from '../models/Manga';
import {
    type MangaCreate,
    MangaCreateFromJSON,
    MangaCreateToJSON,
} from '../models/MangaCreate';

export interface CreateMangaApiV1MangasCreatePostRequest {
    /**
     *
     */
    mangaCreate: MangaCreate;
}

export interface CreateMangaListApiV1MangasCreateListPostRequest {
    /**
     *
     */
    mangaCreate: Array<MangaCreate>;
}

export interface DeleteMangaApiV1MangasMangaIdDeleteRequest {
    /**
     *
     */
    mangaId: number;
}

export interface GetMangaByIdApiV1MangasMangaIdGetRequest {
    /**
     *
     */
    mangaId: number;
}

export interface GetMangasApiV1MangasGetAllGetRequest {
    /**
     *
     */
    skip?: number;
    /**
     *
     */
    limit?: number;
    /**
     * Search term for title
     */
    search?: string | null;
    /**
     * Sort by title
     */
    sort?: string | null;
    /**
     * Filter by categories
     */
    categories?: Array<string> | null;
    /**
     * Filter by reading statuses
     */
    readingStatuses?: Array<string> | null;
    /**
     * Filter by overall statuses
     */
    overallStatuses?: Array<string> | null;
    /**
     * Minimum rating
     */
    ratingMin?: number | null;
    /**
     * Maximum rating
     */
    ratingMax?: number | null;
}

export interface GetMangasByAuthorApiV1MangasByAuthorAuthorIdGetRequest {
    /**
     *
     */
    authorId: number;
}

export interface GetMangasByGenreApiV1MangasByGenreGenreIdGetRequest {
    /**
     *
     */
    genreId: number;
}

export interface GetMangasByListApiV1MangasByListListIdGetRequest {
    /**
     *
     */
    listId: number;
}

export interface GetMangasByStarRatingApiV1MangasByRatingRatingGetRequest {
    /**
     *
     */
    rating: number;
}

export interface UpdateMangaApiV1MangasUpdatePutRequest {
    /**
     *
     */
    manga: Manga;
}

/**
 *
 */
export class MangasApi extends runtime.BaseAPI {

    /**
     * Creates request options for createMangaApiV1MangasCreatePost without sending the request
     */
    async createMangaApiV1MangasCreatePostRequestOpts(requestParameters: CreateMangaApiV1MangasCreatePostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['mangaCreate'] == null) {
            throw new runtime.RequiredError(
                'mangaCreate',
                'Required parameter "mangaCreate" was null or undefined when calling createMangaApiV1MangasCreatePost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v1/mangas/create`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: MangaCreateToJSON(requestParameters['mangaCreate']),
        };
    }

    /**
     * Create Manga
     */
    async createMangaApiV1MangasCreatePostRaw(requestParameters: CreateMangaApiV1MangasCreatePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Manga>> {
        const requestOptions = await this.createMangaApiV1MangasCreatePostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MangaFromJSON(jsonValue));
    }

    /**
     * Create Manga
     */
    async createMangaApiV1MangasCreatePost(requestParameters: CreateMangaApiV1MangasCreatePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Manga> {
        const response = await this.createMangaApiV1MangasCreatePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for createMangaListApiV1MangasCreateListPost without sending the request
     */
    async createMangaListApiV1MangasCreateListPostRequestOpts(requestParameters: CreateMangaListApiV1MangasCreateListPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['mangaCreate'] == null) {
            throw new runtime.RequiredError(
                'mangaCreate',
                'Required parameter "mangaCreate" was null or undefined when calling createMangaListApiV1MangasCreateListPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v1/mangas/create-list`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['mangaCreate']!.map(MangaCreateToJSON),
        };
    }

    /**
     * Create Manga List
     */
    async createMangaListApiV1MangasCreateListPostRaw(requestParameters: CreateMangaListApiV1MangasCreateListPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Manga>>> {
        const requestOptions = await this.createMangaListApiV1MangasCreateListPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(MangaFromJSON));
    }

    /**
     * Create Manga List
     */
    async createMangaListApiV1MangasCreateListPost(requestParameters: CreateMangaListApiV1MangasCreateListPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Manga>> {
        const response = await this.createMangaListApiV1MangasCreateListPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deleteMangaApiV1MangasMangaIdDelete without sending the request
     */
    async deleteMangaApiV1MangasMangaIdDeleteRequestOpts(requestParameters: DeleteMangaApiV1MangasMangaIdDeleteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['mangaId'] == null) {
            throw new runtime.RequiredError(
                'mangaId',
                'Required parameter "mangaId" was null or undefined when calling deleteMangaApiV1MangasMangaIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v1/mangas/{manga_id}`;
        urlPath = urlPath.replace('{manga_id}', encodeURIComponent(String(requestParameters['mangaId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Delete Manga
     */
    async deleteMangaApiV1MangasMangaIdDeleteRaw(requestParameters: DeleteMangaApiV1MangasMangaIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Manga>> {
        const requestOptions = await this.deleteMangaApiV1MangasMangaIdDeleteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MangaFromJSON(jsonValue));
    }

    /**
     * Delete Manga
     */
    async deleteMangaApiV1MangasMangaIdDelete(requestParameters: DeleteMangaApiV1MangasMangaIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Manga> {
        const response = await this.deleteMangaApiV1MangasMangaIdDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getMangaByIdApiV1MangasMangaIdGet without sending the request
     */
    async getMangaByIdApiV1MangasMangaIdGetRequestOpts(requestParameters: GetMangaByIdApiV1MangasMangaIdGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['mangaId'] == null) {
            throw new runtime.RequiredError(
                'mangaId',
                'Required parameter "mangaId" was null or undefined when calling getMangaByIdApiV1MangasMangaIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v1/mangas/{manga_id}`;
        urlPath = urlPath.replace('{manga_id}', encodeURIComponent(String(requestParameters['mangaId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get Manga By Id
     */
    async getMangaByIdApiV1MangasMangaIdGetRaw(requestParameters: GetMangaByIdApiV1MangasMangaIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Manga>> {
        const requestOptions = await this.getMangaByIdApiV1MangasMangaIdGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MangaFromJSON(jsonValue));
    }

    /**
     * Get Manga By Id
     */
    async getMangaByIdApiV1MangasMangaIdGet(requestParameters: GetMangaByIdApiV1MangasMangaIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Manga> {
        const response = await this.getMangaByIdApiV1MangasMangaIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getMangasApiV1MangasGetAllGet without sending the request
     */
    async getMangasApiV1MangasGetAllGetRequestOpts(requestParameters: GetMangasApiV1MangasGetAllGetRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['skip'] != null) {
            queryParameters['skip'] = requestParameters['skip'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['search'] != null) {
            queryParameters['search'] = requestParameters['search'];
        }

        if (requestParameters['sort'] != null) {
            queryParameters['sort'] = requestParameters['sort'];
        }

        if (requestParameters['categories'] != null) {
            queryParameters['categories'] = requestParameters['categories'];
        }

        if (requestParameters['readingStatuses'] != null) {
            queryParameters['reading_statuses'] = requestParameters['readingStatuses'];
        }

        if (requestParameters['overallStatuses'] != null) {
            queryParameters['overall_statuses'] = requestParameters['overallStatuses'];
        }

        if (requestParameters['ratingMin'] != null) {
            queryParameters['rating_min'] = requestParameters['ratingMin'];
        }

        if (requestParameters['ratingMax'] != null) {
            queryParameters['rating_max'] = requestParameters['ratingMax'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v1/mangas/getAll`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Delivers a paginated list of mangas. Optional search (title LIKE), filters (category, status, rating), and sort order can be specified.
     * Get mangas with server-side paging, search and sort
     */
    async getMangasApiV1MangasGetAllGetRaw(requestParameters: GetMangasApiV1MangasGetAllGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Manga>>> {
        const requestOptions = await this.getMangasApiV1MangasGetAllGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(MangaFromJSON));
    }

    /**
     * Delivers a paginated list of mangas. Optional search (title LIKE), filters (category, status, rating), and sort order can be specified.
     * Get mangas with server-side paging, search and sort
     */
    async getMangasApiV1MangasGetAllGet(requestParameters: GetMangasApiV1MangasGetAllGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Manga>> {
        const response = await this.getMangasApiV1MangasGetAllGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getMangasByAuthorApiV1MangasByAuthorAuthorIdGet without sending the request
     */
    async getMangasByAuthorApiV1MangasByAuthorAuthorIdGetRequestOpts(requestParameters: GetMangasByAuthorApiV1MangasByAuthorAuthorIdGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['authorId'] == null) {
            throw new runtime.RequiredError(
                'authorId',
                'Required parameter "authorId" was null or undefined when calling getMangasByAuthorApiV1MangasByAuthorAuthorIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v1/mangas/by-author/{author_id}`;
        urlPath = urlPath.replace('{author_id}', encodeURIComponent(String(requestParameters['authorId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get Mangas By Author
     */
    async getMangasByAuthorApiV1MangasByAuthorAuthorIdGetRaw(requestParameters: GetMangasByAuthorApiV1MangasByAuthorAuthorIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Manga>>> {
        const requestOptions = await this.getMangasByAuthorApiV1MangasByAuthorAuthorIdGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(MangaFromJSON));
    }

    /**
     * Get Mangas By Author
     */
    async getMangasByAuthorApiV1MangasByAuthorAuthorIdGet(requestParameters: GetMangasByAuthorApiV1MangasByAuthorAuthorIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Manga>> {
        const response = await this.getMangasByAuthorApiV1MangasByAuthorAuthorIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getMangasByGenreApiV1MangasByGenreGenreIdGet without sending the request
     */
    async getMangasByGenreApiV1MangasByGenreGenreIdGetRequestOpts(requestParameters: GetMangasByGenreApiV1MangasByGenreGenreIdGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['genreId'] == null) {
            throw new runtime.RequiredError(
                'genreId',
                'Required parameter "genreId" was null or undefined when calling getMangasByGenreApiV1MangasByGenreGenreIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v1/mangas/by-genre/{genre_id}`;
        urlPath = urlPath.replace('{genre_id}', encodeURIComponent(String(requestParameters['genreId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get Mangas By Genre
     */
    async getMangasByGenreApiV1MangasByGenreGenreIdGetRaw(requestParameters: GetMangasByGenreApiV1MangasByGenreGenreIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Manga>>> {
        const requestOptions = await this.getMangasByGenreApiV1MangasByGenreGenreIdGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(MangaFromJSON));
    }

    /**
     * Get Mangas By Genre
     */
    async getMangasByGenreApiV1MangasByGenreGenreIdGet(requestParameters: GetMangasByGenreApiV1MangasByGenreGenreIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Manga>> {
        const response = await this.getMangasByGenreApiV1MangasByGenreGenreIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getMangasByListApiV1MangasByListListIdGet without sending the request
     */
    async getMangasByListApiV1MangasByListListIdGetRequestOpts(requestParameters: GetMangasByListApiV1MangasByListListIdGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['listId'] == null) {
            throw new runtime.RequiredError(
                'listId',
                'Required parameter "listId" was null or undefined when calling getMangasByListApiV1MangasByListListIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v1/mangas/by-list/{list_id}`;
        urlPath = urlPath.replace('{list_id}', encodeURIComponent(String(requestParameters['listId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get Mangas By List
     */
    async getMangasByListApiV1MangasByListListIdGetRaw(requestParameters: GetMangasByListApiV1MangasByListListIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Manga>>> {
        const requestOptions = await this.getMangasByListApiV1MangasByListListIdGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(MangaFromJSON));
    }

    /**
     * Get Mangas By List
     */
    async getMangasByListApiV1MangasByListListIdGet(requestParameters: GetMangasByListApiV1MangasByListListIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Manga>> {
        const response = await this.getMangasByListApiV1MangasByListListIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getMangasByStarRatingApiV1MangasByRatingRatingGet without sending the request
     */
    async getMangasByStarRatingApiV1MangasByRatingRatingGetRequestOpts(requestParameters: GetMangasByStarRatingApiV1MangasByRatingRatingGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['rating'] == null) {
            throw new runtime.RequiredError(
                'rating',
                'Required parameter "rating" was null or undefined when calling getMangasByStarRatingApiV1MangasByRatingRatingGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v1/mangas/by-rating/{rating}`;
        urlPath = urlPath.replace('{rating}', encodeURIComponent(String(requestParameters['rating'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get Mangas By Star Rating
     */
    async getMangasByStarRatingApiV1MangasByRatingRatingGetRaw(requestParameters: GetMangasByStarRatingApiV1MangasByRatingRatingGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Manga>>> {
        const requestOptions = await this.getMangasByStarRatingApiV1MangasByRatingRatingGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(MangaFromJSON));
    }

    /**
     * Get Mangas By Star Rating
     */
    async getMangasByStarRatingApiV1MangasByRatingRatingGet(requestParameters: GetMangasByStarRatingApiV1MangasByRatingRatingGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Manga>> {
        const response = await this.getMangasByStarRatingApiV1MangasByRatingRatingGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateMangaApiV1MangasUpdatePut without sending the request
     */
    async updateMangaApiV1MangasUpdatePutRequestOpts(requestParameters: UpdateMangaApiV1MangasUpdatePutRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['manga'] == null) {
            throw new runtime.RequiredError(
                'manga',
                'Required parameter "manga" was null or undefined when calling updateMangaApiV1MangasUpdatePut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v1/mangas/update`;

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: MangaToJSON(requestParameters['manga']),
        };
    }

    /**
     * Update Manga
     */
    async updateMangaApiV1MangasUpdatePutRaw(requestParameters: UpdateMangaApiV1MangasUpdatePutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Manga>> {
        const requestOptions = await this.updateMangaApiV1MangasUpdatePutRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MangaFromJSON(jsonValue));
    }

    /**
     * Update Manga
     */
    async updateMangaApiV1MangasUpdatePut(requestParameters: UpdateMangaApiV1MangasUpdatePutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Manga> {
        const response = await this.updateMangaApiV1MangasUpdatePutRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
