/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  HTTPValidationError,
  Manga,
  MangaCreate,
} from '../models/index';
import {
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    MangaFromJSON,
    MangaToJSON,
    MangaCreateFromJSON,
    MangaCreateToJSON,
} from '../models/index';

export interface CreateMangaApiV1MangasCreatePostRequest {
    mangaCreate: MangaCreate;
}

export interface CreateMangaListApiV1MangasCreateListPostRequest {
    mangaCreate: Array<MangaCreate>;
}

export interface DeleteMangaApiV1MangasMangaIdDeleteRequest {
    mangaId: number;
}

export interface GetMangaByIdApiV1MangasMangaIdGetRequest {
    mangaId: number;
}

export interface GetMangasApiV1MangasGetAllGetRequest {
    skip?: number;
    limit?: number;
    search?: string | null;
    sort?: string | null;
}

export interface GetMangasByAuthorApiV1MangasByAuthorAuthorIdGetRequest {
    authorId: number;
}

export interface GetMangasByGenreApiV1MangasByGenreGenreIdGetRequest {
    genreId: number;
}

export interface GetMangasByListApiV1MangasByListListIdGetRequest {
    listId: number;
}

export interface GetMangasByStarRatingApiV1MangasByRatingRatingGetRequest {
    rating: number;
}

export interface UpdateMangaApiV1MangasUpdatePutRequest {
    manga: Manga;
}

/**
 *
 */
export class MangasApi extends runtime.BaseAPI {

    /**
     * Create Manga
     */
    async createMangaApiV1MangasCreatePostRaw(requestParameters: CreateMangaApiV1MangasCreatePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Manga>> {
        if (requestParameters['mangaCreate'] == null) {
            throw new runtime.RequiredError(
                'mangaCreate',
                'Required parameter "mangaCreate" was null or undefined when calling createMangaApiV1MangasCreatePost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }

        const response = await this.request({
            path: `/api/v1/mangas/create`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: MangaCreateToJSON(requestParameters['mangaCreate']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MangaFromJSON(jsonValue));
    }

    /**
     * Create Manga
     */
    async createMangaApiV1MangasCreatePost(requestParameters: CreateMangaApiV1MangasCreatePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Manga> {
        const response = await this.createMangaApiV1MangasCreatePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Create Manga List
     */
    async createMangaListApiV1MangasCreateListPostRaw(requestParameters: CreateMangaListApiV1MangasCreateListPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Manga>>> {
        if (requestParameters['mangaCreate'] == null) {
            throw new runtime.RequiredError(
                'mangaCreate',
                'Required parameter "mangaCreate" was null or undefined when calling createMangaListApiV1MangasCreateListPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }

        const response = await this.request({
            path: `/api/v1/mangas/create-list`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['mangaCreate']!.map(MangaCreateToJSON),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(MangaFromJSON));
    }

    /**
     * Create Manga List
     */
    async createMangaListApiV1MangasCreateListPost(requestParameters: CreateMangaListApiV1MangasCreateListPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Manga>> {
        const response = await this.createMangaListApiV1MangasCreateListPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete Manga
     */
    async deleteMangaApiV1MangasMangaIdDeleteRaw(requestParameters: DeleteMangaApiV1MangasMangaIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Manga>> {
        if (requestParameters['mangaId'] == null) {
            throw new runtime.RequiredError(
                'mangaId',
                'Required parameter "mangaId" was null or undefined when calling deleteMangaApiV1MangasMangaIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }

        const response = await this.request({
            path: `/api/v1/mangas/{manga_id}`.replace(`{${"manga_id"}}`, encodeURIComponent(String(requestParameters['mangaId']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MangaFromJSON(jsonValue));
    }

    /**
     * Delete Manga
     */
    async deleteMangaApiV1MangasMangaIdDelete(requestParameters: DeleteMangaApiV1MangasMangaIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Manga> {
        const response = await this.deleteMangaApiV1MangasMangaIdDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get Manga By Id
     */
    async getMangaByIdApiV1MangasMangaIdGetRaw(requestParameters: GetMangaByIdApiV1MangasMangaIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Manga>> {
        if (requestParameters['mangaId'] == null) {
            throw new runtime.RequiredError(
                'mangaId',
                'Required parameter "mangaId" was null or undefined when calling getMangaByIdApiV1MangasMangaIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }

        const response = await this.request({
            path: `/api/v1/mangas/{manga_id}`.replace(`{${"manga_id"}}`, encodeURIComponent(String(requestParameters['mangaId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MangaFromJSON(jsonValue));
    }

    /**
     * Get Manga By Id
     */
    async getMangaByIdApiV1MangasMangaIdGet(requestParameters: GetMangaByIdApiV1MangasMangaIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Manga> {
        const response = await this.getMangaByIdApiV1MangasMangaIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Liefert eine paginierte Liste von Mangas zurück. Optional können Suchbegriff (title LIKE) und Sortierreihenfolge angegeben werden.
     * Get mangas with server-side paging, search and sort
     */
    async getMangasApiV1MangasGetAllGetRaw(requestParameters: GetMangasApiV1MangasGetAllGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Manga>>> {
        const queryParameters: any = {};

        if (requestParameters['skip'] != null) {
            queryParameters['skip'] = requestParameters['skip'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['search'] != null) {
            queryParameters['search'] = requestParameters['search'];
        }

        if (requestParameters['sort'] != null) {
            queryParameters['sort'] = requestParameters['sort'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }

        const response = await this.request({
            path: `/api/v1/mangas/getAll`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(MangaFromJSON));
    }

    /**
     * Liefert eine paginierte Liste von Mangas zurück. Optional können Suchbegriff (title LIKE) und Sortierreihenfolge angegeben werden.
     * Get mangas with server-side paging, search and sort
     */
    async getMangasApiV1MangasGetAllGet(requestParameters: GetMangasApiV1MangasGetAllGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Manga>> {
        const response = await this.getMangasApiV1MangasGetAllGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get Mangas By Author
     */
    async getMangasByAuthorApiV1MangasByAuthorAuthorIdGetRaw(requestParameters: GetMangasByAuthorApiV1MangasByAuthorAuthorIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Manga>>> {
        if (requestParameters['authorId'] == null) {
            throw new runtime.RequiredError(
                'authorId',
                'Required parameter "authorId" was null or undefined when calling getMangasByAuthorApiV1MangasByAuthorAuthorIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }

        const response = await this.request({
            path: `/api/v1/mangas/by-author/{author_id}`.replace(`{${"author_id"}}`, encodeURIComponent(String(requestParameters['authorId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(MangaFromJSON));
    }

    /**
     * Get Mangas By Author
     */
    async getMangasByAuthorApiV1MangasByAuthorAuthorIdGet(requestParameters: GetMangasByAuthorApiV1MangasByAuthorAuthorIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Manga>> {
        const response = await this.getMangasByAuthorApiV1MangasByAuthorAuthorIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get Mangas By Genre
     */
    async getMangasByGenreApiV1MangasByGenreGenreIdGetRaw(requestParameters: GetMangasByGenreApiV1MangasByGenreGenreIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Manga>>> {
        if (requestParameters['genreId'] == null) {
            throw new runtime.RequiredError(
                'genreId',
                'Required parameter "genreId" was null or undefined when calling getMangasByGenreApiV1MangasByGenreGenreIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }

        const response = await this.request({
            path: `/api/v1/mangas/by-genre/{genre_id}`.replace(`{${"genre_id"}}`, encodeURIComponent(String(requestParameters['genreId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(MangaFromJSON));
    }

    /**
     * Get Mangas By Genre
     */
    async getMangasByGenreApiV1MangasByGenreGenreIdGet(requestParameters: GetMangasByGenreApiV1MangasByGenreGenreIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Manga>> {
        const response = await this.getMangasByGenreApiV1MangasByGenreGenreIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get Mangas By List
     */
    async getMangasByListApiV1MangasByListListIdGetRaw(requestParameters: GetMangasByListApiV1MangasByListListIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Manga>>> {
        if (requestParameters['listId'] == null) {
            throw new runtime.RequiredError(
                'listId',
                'Required parameter "listId" was null or undefined when calling getMangasByListApiV1MangasByListListIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }

        const response = await this.request({
            path: `/api/v1/mangas/by-list/{list_id}`.replace(`{${"list_id"}}`, encodeURIComponent(String(requestParameters['listId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(MangaFromJSON));
    }

    /**
     * Get Mangas By List
     */
    async getMangasByListApiV1MangasByListListIdGet(requestParameters: GetMangasByListApiV1MangasByListListIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Manga>> {
        const response = await this.getMangasByListApiV1MangasByListListIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get Mangas By Star Rating
     */
    async getMangasByStarRatingApiV1MangasByRatingRatingGetRaw(requestParameters: GetMangasByStarRatingApiV1MangasByRatingRatingGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Manga>>> {
        if (requestParameters['rating'] == null) {
            throw new runtime.RequiredError(
                'rating',
                'Required parameter "rating" was null or undefined when calling getMangasByStarRatingApiV1MangasByRatingRatingGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }

        const response = await this.request({
            path: `/api/v1/mangas/by-rating/{rating}`.replace(`{${"rating"}}`, encodeURIComponent(String(requestParameters['rating']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(MangaFromJSON));
    }

    /**
     * Get Mangas By Star Rating
     */
    async getMangasByStarRatingApiV1MangasByRatingRatingGet(requestParameters: GetMangasByStarRatingApiV1MangasByRatingRatingGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Manga>> {
        const response = await this.getMangasByStarRatingApiV1MangasByRatingRatingGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update Manga
     */
    async updateMangaApiV1MangasUpdatePutRaw(requestParameters: UpdateMangaApiV1MangasUpdatePutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Manga>> {
        if (requestParameters['manga'] == null) {
            throw new runtime.RequiredError(
                'manga',
                'Required parameter "manga" was null or undefined when calling updateMangaApiV1MangasUpdatePut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }

        const response = await this.request({
            path: `/api/v1/mangas/update`,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: MangaToJSON(requestParameters['manga']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MangaFromJSON(jsonValue));
    }

    /**
     * Update Manga
     */
    async updateMangaApiV1MangasUpdatePut(requestParameters: UpdateMangaApiV1MangasUpdatePutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Manga> {
        const response = await this.updateMangaApiV1MangasUpdatePutRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
