/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  HTTPValidationError,
} from '../models/index';
import {
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
} from '../models/index';

export interface CreateOrUpdateSettingApiV1SettingsKeyPostRequest {
    key: string;
    value: string;
    migrate?: boolean;
}

export interface GetSettingApiV1SettingsKeyGetRequest {
    key: string;
}

/**
 *
 */
export class SettingsApi extends runtime.BaseAPI {

    /**
     * Create Or Update Setting
     */
    async createOrUpdateSettingApiV1SettingsKeyPostRaw(requestParameters: CreateOrUpdateSettingApiV1SettingsKeyPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['key'] == null) {
            throw new runtime.RequiredError(
                'key',
                'Required parameter "key" was null or undefined when calling createOrUpdateSettingApiV1SettingsKeyPost().'
            );
        }

        if (requestParameters['value'] == null) {
            throw new runtime.RequiredError(
                'value',
                'Required parameter "value" was null or undefined when calling createOrUpdateSettingApiV1SettingsKeyPost().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['value'] != null) {
            queryParameters['value'] = requestParameters['value'];
        }

        if (requestParameters['migrate'] != null) {
            queryParameters['migrate'] = requestParameters['migrate'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/settings/{key}`.replace(`{${"key"}}`, encodeURIComponent(String(requestParameters['key']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Create Or Update Setting
     */
    async createOrUpdateSettingApiV1SettingsKeyPost(requestParameters: CreateOrUpdateSettingApiV1SettingsKeyPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.createOrUpdateSettingApiV1SettingsKeyPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get All Settings
     */
    async getAllSettingsApiV1SettingsGetAllGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/settings/getAll`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Get All Settings
     */
    async getAllSettingsApiV1SettingsGetAllGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.getAllSettingsApiV1SettingsGetAllGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Get Setting
     */
    async getSettingApiV1SettingsKeyGetRaw(requestParameters: GetSettingApiV1SettingsKeyGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['key'] == null) {
            throw new runtime.RequiredError(
                'key',
                'Required parameter "key" was null or undefined when calling getSettingApiV1SettingsKeyGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/settings/{key}`.replace(`{${"key"}}`, encodeURIComponent(String(requestParameters['key']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Get Setting
     */
    async getSettingApiV1SettingsKeyGet(requestParameters: GetSettingApiV1SettingsKeyGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.getSettingApiV1SettingsKeyGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
