/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type HTTPValidationError,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
} from '../models/HTTPValidationError';

export interface CreateOrUpdateSettingApiV1SettingsKeyPostRequest {
    /**
     *
     */
    key: string;
    /**
     *
     */
    value: string;
    /**
     *
     */
    migrate?: boolean;
}

export interface GetSettingApiV1SettingsKeyGetRequest {
    /**
     *
     */
    key: string;
}

/**
 *
 */
export class SettingsApi extends runtime.BaseAPI {

    /**
     * Creates request options for createOrUpdateSettingApiV1SettingsKeyPost without sending the request
     */
    async createOrUpdateSettingApiV1SettingsKeyPostRequestOpts(requestParameters: CreateOrUpdateSettingApiV1SettingsKeyPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['key'] == null) {
            throw new runtime.RequiredError(
                'key',
                'Required parameter "key" was null or undefined when calling createOrUpdateSettingApiV1SettingsKeyPost().'
            );
        }

        if (requestParameters['value'] == null) {
            throw new runtime.RequiredError(
                'value',
                'Required parameter "value" was null or undefined when calling createOrUpdateSettingApiV1SettingsKeyPost().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['value'] != null) {
            queryParameters['value'] = requestParameters['value'];
        }

        if (requestParameters['migrate'] != null) {
            queryParameters['migrate'] = requestParameters['migrate'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/settings/{key}`;
        urlPath = urlPath.replace('{key}', encodeURIComponent(String(requestParameters['key'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Create Or Update Setting
     */
    async createOrUpdateSettingApiV1SettingsKeyPostRaw(requestParameters: CreateOrUpdateSettingApiV1SettingsKeyPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const requestOptions = await this.createOrUpdateSettingApiV1SettingsKeyPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Create Or Update Setting
     */
    async createOrUpdateSettingApiV1SettingsKeyPost(requestParameters: CreateOrUpdateSettingApiV1SettingsKeyPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.createOrUpdateSettingApiV1SettingsKeyPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getAllSettingsApiV1SettingsGetAllGet without sending the request
     */
    async getAllSettingsApiV1SettingsGetAllGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/settings/getAll`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get All Settings
     */
    async getAllSettingsApiV1SettingsGetAllGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const requestOptions = await this.getAllSettingsApiV1SettingsGetAllGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Get All Settings
     */
    async getAllSettingsApiV1SettingsGetAllGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.getAllSettingsApiV1SettingsGetAllGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getSettingApiV1SettingsKeyGet without sending the request
     */
    async getSettingApiV1SettingsKeyGetRequestOpts(requestParameters: GetSettingApiV1SettingsKeyGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['key'] == null) {
            throw new runtime.RequiredError(
                'key',
                'Required parameter "key" was null or undefined when calling getSettingApiV1SettingsKeyGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/settings/{key}`;
        urlPath = urlPath.replace('{key}', encodeURIComponent(String(requestParameters['key'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get Setting
     */
    async getSettingApiV1SettingsKeyGetRaw(requestParameters: GetSettingApiV1SettingsKeyGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const requestOptions = await this.getSettingApiV1SettingsKeyGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Get Setting
     */
    async getSettingApiV1SettingsKeyGet(requestParameters: GetSettingApiV1SettingsKeyGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.getSettingApiV1SettingsKeyGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
