/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type HTTPValidationError,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
} from '../models/HTTPValidationError';
import {
    type MangaCreate,
    MangaCreateFromJSON,
    MangaCreateToJSON,
} from '../models/MangaCreate';
import {
    type Source,
    SourceFromJSON,
    SourceToJSON,
} from '../models/Source';
import {
    type SourceCreate,
    SourceCreateFromJSON,
    SourceCreateToJSON,
} from '../models/SourceCreate';

export interface CreateSourceApiV1SourcesCreatePostRequest {
    /**
     *
     */
    sourceCreate: SourceCreate;
}

export interface SearchMangaApiV1SourcesSearchPostRequest {
    /**
     *
     */
    title: string;
    /**
     *
     */
    sourceName: string;
}

/**
 *
 */
export class SourcesApi extends runtime.BaseAPI {

    /**
     * Creates request options for createSourceApiV1SourcesCreatePost without sending the request
     */
    async createSourceApiV1SourcesCreatePostRequestOpts(requestParameters: CreateSourceApiV1SourcesCreatePostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['sourceCreate'] == null) {
            throw new runtime.RequiredError(
                'sourceCreate',
                'Required parameter "sourceCreate" was null or undefined when calling createSourceApiV1SourcesCreatePost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/sources/create`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SourceCreateToJSON(requestParameters['sourceCreate']),
        };
    }

    /**
     * Create Source
     */
    async createSourceApiV1SourcesCreatePostRaw(requestParameters: CreateSourceApiV1SourcesCreatePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Source>> {
        const requestOptions = await this.createSourceApiV1SourcesCreatePostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SourceFromJSON(jsonValue));
    }

    /**
     * Create Source
     */
    async createSourceApiV1SourcesCreatePost(requestParameters: CreateSourceApiV1SourcesCreatePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Source> {
        const response = await this.createSourceApiV1SourcesCreatePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getSourcesApiV1SourcesGetAllGet without sending the request
     */
    async getSourcesApiV1SourcesGetAllGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/sources/getAll`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get Sources
     */
    async getSourcesApiV1SourcesGetAllGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Source>>> {
        const requestOptions = await this.getSourcesApiV1SourcesGetAllGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(SourceFromJSON));
    }

    /**
     * Get Sources
     */
    async getSourcesApiV1SourcesGetAllGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Source>> {
        const response = await this.getSourcesApiV1SourcesGetAllGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for searchMangaApiV1SourcesSearchPost without sending the request
     */
    async searchMangaApiV1SourcesSearchPostRequestOpts(requestParameters: SearchMangaApiV1SourcesSearchPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['title'] == null) {
            throw new runtime.RequiredError(
                'title',
                'Required parameter "title" was null or undefined when calling searchMangaApiV1SourcesSearchPost().'
            );
        }

        if (requestParameters['sourceName'] == null) {
            throw new runtime.RequiredError(
                'sourceName',
                'Required parameter "sourceName" was null or undefined when calling searchMangaApiV1SourcesSearchPost().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['title'] != null) {
            queryParameters['title'] = requestParameters['title'];
        }

        if (requestParameters['sourceName'] != null) {
            queryParameters['source_name'] = requestParameters['sourceName'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/sources/search`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Search Manga
     */
    async searchMangaApiV1SourcesSearchPostRaw(requestParameters: SearchMangaApiV1SourcesSearchPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<MangaCreate>>> {
        const requestOptions = await this.searchMangaApiV1SourcesSearchPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(MangaCreateFromJSON));
    }

    /**
     * Search Manga
     */
    async searchMangaApiV1SourcesSearchPost(requestParameters: SearchMangaApiV1SourcesSearchPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<MangaCreate>> {
        const response = await this.searchMangaApiV1SourcesSearchPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
