/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type Statistics,
    StatisticsFromJSON,
    StatisticsToJSON,
} from '../models/Statistics';

/**
 *
 */
export class StatisticsApi extends runtime.BaseAPI {

    /**
     * Creates request options for getStatisticsApiV1StatisticsGet without sending the request
     */
    async getStatisticsApiV1StatisticsGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/statistics/`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get Statistics
     */
    async getStatisticsApiV1StatisticsGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Statistics>> {
        const requestOptions = await this.getStatisticsApiV1StatisticsGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StatisticsFromJSON(jsonValue));
    }

    /**
     * Get Statistics
     */
    async getStatisticsApiV1StatisticsGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Statistics> {
        const response = await this.getStatisticsApiV1StatisticsGetRaw(initOverrides);
        return await response.value();
    }

}
