/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  HTTPValidationError,
  UserUpdatePassword,
} from '../models/index';
import {
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    UserUpdatePasswordFromJSON,
    UserUpdatePasswordToJSON,
} from '../models/index';

export interface ChangePasswordApiV1UsersChangePasswordPostRequest {
    userUpdatePassword: UserUpdatePassword;
}

/**
 *
 */
export class UsersApi extends runtime.BaseAPI {

    /**
     * Change password for a user. Only accessible by admin.
     * Change Password
     */
    async changePasswordApiV1UsersChangePasswordPostRaw(requestParameters: ChangePasswordApiV1UsersChangePasswordPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['userUpdatePassword'] == null) {
            throw new runtime.RequiredError(
                'userUpdatePassword',
                'Required parameter "userUpdatePassword" was null or undefined when calling changePasswordApiV1UsersChangePasswordPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }

        const response = await this.request({
            path: `/api/v1/users/change-password`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: UserUpdatePasswordToJSON(requestParameters['userUpdatePassword']),
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Change password for a user. Only accessible by admin.
     * Change Password
     */
    async changePasswordApiV1UsersChangePasswordPost(requestParameters: ChangePasswordApiV1UsersChangePasswordPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.changePasswordApiV1UsersChangePasswordPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
