/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Volume
 */
export interface Volume {
    /**
     * 
     * @type {string}
     * @memberof Volume
     */
    volumeNumber: string;
    /**
     * 
     * @type {string}
     * @memberof Volume
     */
    coverImage?: string | null;
    /**
     * 
     * @type {number}
     * @memberof Volume
     */
    id: number;
    /**
     * 
     * @type {number}
     * @memberof Volume
     */
    mangaId: number;
}

/**
 * Check if a given object implements the Volume interface.
 */
export function instanceOfVolume(value: object): value is Volume {
    if (!('volumeNumber' in value) || value['volumeNumber'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('mangaId' in value) || value['mangaId'] === undefined) return false;
    return true;
}

export function VolumeFromJSON(json: any): Volume {
    return VolumeFromJSONTyped(json, false);
}

export function VolumeFromJSONTyped(json: any, ignoreDiscriminator: boolean): Volume {
    if (json == null) {
        return json;
    }
    return {
        
        'volumeNumber': json['volume_number'],
        'coverImage': json['cover_image'] == null ? undefined : json['cover_image'],
        'id': json['id'],
        'mangaId': json['manga_id'],
    };
}

export function VolumeToJSON(json: any): Volume {
    return VolumeToJSONTyped(json, false);
}

export function VolumeToJSONTyped(value?: Volume | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'volume_number': value['volumeNumber'],
        'cover_image': value['coverImage'],
        'id': value['id'],
        'manga_id': value['mangaId'],
    };
}

