/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface Author
 */
export interface Author {
    /**
     *
     * @type {string}
     * @memberof Author
     */
    name: string;
    /**
     *
     * @type {number}
     * @memberof Author
     */
    id: number;
    /**
     *
     * @type {number}
     * @memberof Author
     */
    mangaCount?: number;
}

/**
 * Check if a given object implements the Author interface.
 */
export function instanceOfAuthor(value: object): value is Author {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function AuthorFromJSON(json: any): Author {
    return AuthorFromJSONTyped(json, false);
}

export function AuthorFromJSONTyped(json: any, ignoreDiscriminator: boolean): Author {
    if (json == null) {
        return json;
    }
    return {

        'name': json['name'],
        'id': json['id'],
        'mangaCount': json['manga_count'] == null ? undefined : json['manga_count'],
    };
}

export function AuthorToJSON(json: any): Author {
    return AuthorToJSONTyped(json, false);
}

export function AuthorToJSONTyped(value?: Author | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'name': value['name'],
        'id': value['id'],
        'manga_count': value['mangaCount'],
    };
}
