/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthorCreate
 */
export interface AuthorCreate {
    /**
     * 
     * @type {string}
     * @memberof AuthorCreate
     */
    name: string;
}

/**
 * Check if a given object implements the AuthorCreate interface.
 */
export function instanceOfAuthorCreate(value: object): value is AuthorCreate {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function AuthorCreateFromJSON(json: any): AuthorCreate {
    return AuthorCreateFromJSONTyped(json, false);
}

export function AuthorCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthorCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
    };
}

export function AuthorCreateToJSON(value?: AuthorCreate | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
    };
}

