/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * An enumeration.
 * @export
 */
export const CollectionStatus = {
    NotSet: 'not_set',
    Completed: 'completed',
    Ongoing: 'ongoing',
    Incomplete: 'incomplete',
    Canceled: 'canceled'
} as const;
export type CollectionStatus = typeof CollectionStatus[keyof typeof CollectionStatus];


export function CollectionStatusFromJSON(json: any): CollectionStatus {
    return CollectionStatusFromJSONTyped(json, false);
}

export function CollectionStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): CollectionStatus {
    return json as CollectionStatus;
}

export function CollectionStatusToJSON(value?: CollectionStatus | null): any {
    return value as any;
}

