/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GenreCreate
 */
export interface GenreCreate {
    /**
     * 
     * @type {string}
     * @memberof GenreCreate
     */
    name: string;
}

/**
 * Check if a given object implements the GenreCreate interface.
 */
export function instanceOfGenreCreate(value: object): value is GenreCreate {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function GenreCreateFromJSON(json: any): GenreCreate {
    return GenreCreateFromJSONTyped(json, false);
}

export function GenreCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): GenreCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
    };
}

export function GenreCreateToJSON(value?: GenreCreate | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
    };
}

