/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface ImportResponse
 */
export interface ImportResponse {
    /**
     *
     * @type {number}
     * @memberof ImportResponse
     */
    total: number;
    /**
     *
     * @type {number}
     * @memberof ImportResponse
     */
    imported: number;
    /**
     *
     * @type {number}
     * @memberof ImportResponse
     */
    failed: number;
    /**
     *
     * @type {Array<string>}
     * @memberof ImportResponse
     */
    errors: Array<string>;
}

/**
 * Check if a given object implements the ImportResponse interface.
 */
export function instanceOfImportResponse(value: object): value is ImportResponse {
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('imported' in value) || value['imported'] === undefined) return false;
    if (!('failed' in value) || value['failed'] === undefined) return false;
    if (!('errors' in value) || value['errors'] === undefined) return false;
    return true;
}

export function ImportResponseFromJSON(json: any): ImportResponse {
    return ImportResponseFromJSONTyped(json, false);
}

export function ImportResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ImportResponse {
    if (json == null) {
        return json;
    }
    return {

        'total': json['total'],
        'imported': json['imported'],
        'failed': json['failed'],
        'errors': json['errors'],
    };
}

export function ImportResponseToJSON(json: any): ImportResponse {
    return ImportResponseToJSONTyped(json, false);
}

export function ImportResponseToJSONTyped(value?: ImportResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'total': value['total'],
        'imported': value['imported'],
        'failed': value['failed'],
        'errors': value['errors'],
    };
}
