/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface ImportResultDetail
 */
export interface ImportResultDetail {
    /**
     *
     * @type {string}
     * @memberof ImportResultDetail
     */
    title: string;
    /**
     *
     * @type {string}
     * @memberof ImportResultDetail
     */
    status: string;
    /**
     *
     * @type {string}
     * @memberof ImportResultDetail
     */
    infoCode: string;
}

/**
 * Check if a given object implements the ImportResultDetail interface.
 */
export function instanceOfImportResultDetail(value: object): value is ImportResultDetail {
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('infoCode' in value) || value['infoCode'] === undefined) return false;
    return true;
}

export function ImportResultDetailFromJSON(json: any): ImportResultDetail {
    return ImportResultDetailFromJSONTyped(json, false);
}

export function ImportResultDetailFromJSONTyped(json: any, ignoreDiscriminator: boolean): ImportResultDetail {
    if (json == null) {
        return json;
    }
    return {

        'title': json['title'],
        'status': json['status'],
        'infoCode': json['info_code'],
    };
}

export function ImportResultDetailToJSON(json: any): ImportResultDetail {
    return ImportResultDetailToJSONTyped(json, false);
}

export function ImportResultDetailToJSONTyped(value?: ImportResultDetail | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'title': value['title'],
        'status': value['status'],
        'info_code': value['infoCode'],
    };
}
