/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ListCreate
 */
export interface ListCreate {
    /**
     * 
     * @type {string}
     * @memberof ListCreate
     */
    name: string;
}

/**
 * Check if a given object implements the ListCreate interface.
 */
export function instanceOfListCreate(value: object): value is ListCreate {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function ListCreateFromJSON(json: any): ListCreate {
    return ListCreateFromJSONTyped(json, false);
}

export function ListCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
    };
}

export function ListCreateToJSON(json: any): ListCreate {
    return ListCreateToJSONTyped(json, false);
}

export function ListCreateToJSONTyped(value?: ListCreate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
    };
}

