/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Category } from './Category';
import {
    CategoryFromJSON,
    CategoryFromJSONTyped,
    CategoryToJSON,
    CategoryToJSONTyped,
} from './Category';
import type { ReadingStatus } from './ReadingStatus';
import {
    ReadingStatusFromJSON,
    ReadingStatusFromJSONTyped,
    ReadingStatusToJSON,
    ReadingStatusToJSONTyped,
} from './ReadingStatus';
import type { ListCreate } from './ListCreate';
import {
    ListCreateFromJSON,
    ListCreateFromJSONTyped,
    ListCreateToJSON,
    ListCreateToJSONTyped,
} from './ListCreate';
import type { GenreCreate } from './GenreCreate';
import {
    GenreCreateFromJSON,
    GenreCreateFromJSONTyped,
    GenreCreateToJSON,
    GenreCreateToJSONTyped,
} from './GenreCreate';
import type { AuthorCreate } from './AuthorCreate';
import {
    AuthorCreateFromJSON,
    AuthorCreateFromJSONTyped,
    AuthorCreateToJSON,
    AuthorCreateToJSONTyped,
} from './AuthorCreate';
import type { OverallStatus } from './OverallStatus';
import {
    OverallStatusFromJSON,
    OverallStatusFromJSONTyped,
    OverallStatusToJSON,
    OverallStatusToJSONTyped,
} from './OverallStatus';
import type { VolumeCreate } from './VolumeCreate';
import {
    VolumeCreateFromJSON,
    VolumeCreateFromJSONTyped,
    VolumeCreateToJSON,
    VolumeCreateToJSONTyped,
} from './VolumeCreate';

/**
 * 
 * @export
 * @interface MangaCreate
 */
export interface MangaCreate {
    /**
     * 
     * @type {string}
     * @memberof MangaCreate
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof MangaCreate
     */
    japaneseTitle?: string | null;
    /**
     * 
     * @type {ReadingStatus}
     * @memberof MangaCreate
     */
    readingStatus?: ReadingStatus | null;
    /**
     * 
     * @type {OverallStatus}
     * @memberof MangaCreate
     */
    overallStatus?: OverallStatus | null;
    /**
     * 
     * @type {number}
     * @memberof MangaCreate
     */
    starRating?: number | null;
    /**
     * 
     * @type {string}
     * @memberof MangaCreate
     */
    language?: string | null;
    /**
     * 
     * @type {Category}
     * @memberof MangaCreate
     */
    category: Category;
    /**
     * 
     * @type {string}
     * @memberof MangaCreate
     */
    summary?: string | null;
    /**
     * 
     * @type {string}
     * @memberof MangaCreate
     */
    coverImage?: string | null;
    /**
     * 
     * @type {Array<AuthorCreate>}
     * @memberof MangaCreate
     */
    authors: Array<AuthorCreate>;
    /**
     * 
     * @type {Array<GenreCreate>}
     * @memberof MangaCreate
     */
    genres: Array<GenreCreate>;
    /**
     * 
     * @type {Array<ListCreate>}
     * @memberof MangaCreate
     */
    lists: Array<ListCreate>;
    /**
     * 
     * @type {Array<VolumeCreate>}
     * @memberof MangaCreate
     */
    volumes: Array<VolumeCreate>;
}



/**
 * Check if a given object implements the MangaCreate interface.
 */
export function instanceOfMangaCreate(value: object): value is MangaCreate {
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('category' in value) || value['category'] === undefined) return false;
    if (!('authors' in value) || value['authors'] === undefined) return false;
    if (!('genres' in value) || value['genres'] === undefined) return false;
    if (!('lists' in value) || value['lists'] === undefined) return false;
    if (!('volumes' in value) || value['volumes'] === undefined) return false;
    return true;
}

export function MangaCreateFromJSON(json: any): MangaCreate {
    return MangaCreateFromJSONTyped(json, false);
}

export function MangaCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): MangaCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'],
        'japaneseTitle': json['japanese_title'] == null ? undefined : json['japanese_title'],
        'readingStatus': json['reading_status'] == null ? undefined : ReadingStatusFromJSON(json['reading_status']),
        'overallStatus': json['overall_status'] == null ? undefined : OverallStatusFromJSON(json['overall_status']),
        'starRating': json['star_rating'] == null ? undefined : json['star_rating'],
        'language': json['language'] == null ? undefined : json['language'],
        'category': CategoryFromJSON(json['category']),
        'summary': json['summary'] == null ? undefined : json['summary'],
        'coverImage': json['cover_image'] == null ? undefined : json['cover_image'],
        'authors': ((json['authors'] as Array<any>).map(AuthorCreateFromJSON)),
        'genres': ((json['genres'] as Array<any>).map(GenreCreateFromJSON)),
        'lists': ((json['lists'] as Array<any>).map(ListCreateFromJSON)),
        'volumes': ((json['volumes'] as Array<any>).map(VolumeCreateFromJSON)),
    };
}

export function MangaCreateToJSON(json: any): MangaCreate {
    return MangaCreateToJSONTyped(json, false);
}

export function MangaCreateToJSONTyped(value?: MangaCreate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'japanese_title': value['japaneseTitle'],
        'reading_status': ReadingStatusToJSON(value['readingStatus']),
        'overall_status': OverallStatusToJSON(value['overallStatus']),
        'star_rating': value['starRating'],
        'language': value['language'],
        'category': CategoryToJSON(value['category']),
        'summary': value['summary'],
        'cover_image': value['coverImage'],
        'authors': ((value['authors'] as Array<any>).map(AuthorCreateToJSON)),
        'genres': ((value['genres'] as Array<any>).map(GenreCreateToJSON)),
        'lists': ((value['lists'] as Array<any>).map(ListCreateToJSON)),
        'volumes': ((value['volumes'] as Array<any>).map(VolumeCreateToJSON)),
    };
}

