/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const OverallStatus = {
    Ongoing: 'ongoing',
    Completed: 'completed',
    Hiatus: 'hiatus',
    Cancelled: 'cancelled'
} as const;
export type OverallStatus = typeof OverallStatus[keyof typeof OverallStatus];


export function instanceOfOverallStatus(value: any): boolean {
    for (const key in OverallStatus) {
        if (Object.prototype.hasOwnProperty.call(OverallStatus, key)) {
            if (OverallStatus[key] === value) {
                return true;
            }
        }
    }
    return false;
}

export function OverallStatusFromJSON(json: any): OverallStatus {
    return OverallStatusFromJSONTyped(json, false);
}

export function OverallStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): OverallStatus {
    return json as OverallStatus;
}

export function OverallStatusToJSON(value?: OverallStatus | null): any {
    return value as any;
}

