/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * An enumeration.
 * @export
 */
export const ReadingStatus = {
    NotSet: 'not_set',
    Reading: 'reading',
    Completed: 'completed',
    Canceled: 'canceled'
} as const;
export type ReadingStatus = typeof ReadingStatus[keyof typeof ReadingStatus];


export function ReadingStatusFromJSON(json: any): ReadingStatus {
    return ReadingStatusFromJSONTyped(json, false);
}

export function ReadingStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReadingStatus {
    return json as ReadingStatus;
}

export function ReadingStatusToJSON(value?: ReadingStatus | null): any {
    return value as any;
}

