/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const ReadingStatus = {
    NotStarted: 'not_started',
    InProgress: 'in_progress',
    Completed: 'completed',
    OnHold: 'on_hold',
    Dropped: 'dropped'
} as const;
export type ReadingStatus = typeof ReadingStatus[keyof typeof ReadingStatus];


export function instanceOfReadingStatus(value: any): boolean {
    for (const key in ReadingStatus) {
        if (Object.prototype.hasOwnProperty.call(ReadingStatus, key)) {
            if (ReadingStatus[key] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ReadingStatusFromJSON(json: any): ReadingStatus {
    return ReadingStatusFromJSONTyped(json, false);
}

export function ReadingStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReadingStatus {
    return json as ReadingStatus;
}

export function ReadingStatusToJSON(value?: ReadingStatus | null): any {
    return value as any;
}

