/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface SourceCreate
 */
export interface SourceCreate {
    /**
     *
     * @type {string}
     * @memberof SourceCreate
     */
    name: string;
    /**
     *
     * @type {string}
     * @memberof SourceCreate
     */
    language: string;
}

/**
 * Check if a given object implements the SourceCreate interface.
 */
export function instanceOfSourceCreate(value: object): value is SourceCreate {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('language' in value) || value['language'] === undefined) return false;
    return true;
}

export function SourceCreateFromJSON(json: any): SourceCreate {
    return SourceCreateFromJSONTyped(json, false);
}

export function SourceCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): SourceCreate {
    if (json == null) {
        return json;
    }
    return {

        'name': json['name'],
        'language': json['language'],
    };
}

export function SourceCreateToJSON(json: any): SourceCreate {
    return SourceCreateToJSONTyped(json, false);
}

export function SourceCreateToJSONTyped(value?: SourceCreate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'name': value['name'],
        'language': value['language'],
    };
}
