/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { StatisticCount } from './StatisticCount';
import {
    StatisticCountFromJSON,
    StatisticCountFromJSONTyped,
    StatisticCountToJSON,
    StatisticCountToJSONTyped,
} from './StatisticCount';

/**
 *
 * @export
 * @interface Statistics
 */
export interface Statistics {
    /**
     *
     */
    totalMangas: number;
    /**
     *
     */
    totalVolumes: number;
    /**
     *
     */
    totalAuthors: number;
    /**
     *
     */
    totalGenres: number;
    /**
     *
     */
    totalLists: number;
    /**
     *
     */
    readingStatusDistribution: Array<StatisticCount>;
    /**
     *
     */
    overallStatusDistribution: Array<StatisticCount>;
    /**
     *
     */
    categoryDistribution: Array<StatisticCount>;
    /**
     *
     */
    ratingDistribution: Array<StatisticCount>;
    /**
     *
     */
    topGenres: Array<StatisticCount>;
    /**
     *
     */
    topAuthors: Array<StatisticCount>;
}

/**
 * Check if a given object implements the Statistics interface.
 */
export function instanceOfStatistics(value: object): value is Statistics {
    if ((!('totalMangas' in (value as Record<string, any>)) && !('total_mangas' in (value as Record<string, any>))) || ((value as Record<string, any>)['totalMangas'] === undefined && (value as Record<string, any>)['total_mangas'] === undefined)) return false;
    if ((!('totalVolumes' in (value as Record<string, any>)) && !('total_volumes' in (value as Record<string, any>))) || ((value as Record<string, any>)['totalVolumes'] === undefined && (value as Record<string, any>)['total_volumes'] === undefined)) return false;
    if ((!('totalAuthors' in (value as Record<string, any>)) && !('total_authors' in (value as Record<string, any>))) || ((value as Record<string, any>)['totalAuthors'] === undefined && (value as Record<string, any>)['total_authors'] === undefined)) return false;
    if ((!('totalGenres' in (value as Record<string, any>)) && !('total_genres' in (value as Record<string, any>))) || ((value as Record<string, any>)['totalGenres'] === undefined && (value as Record<string, any>)['total_genres'] === undefined)) return false;
    if ((!('totalLists' in (value as Record<string, any>)) && !('total_lists' in (value as Record<string, any>))) || ((value as Record<string, any>)['totalLists'] === undefined && (value as Record<string, any>)['total_lists'] === undefined)) return false;
    if ((!('readingStatusDistribution' in (value as Record<string, any>)) && !('reading_status_distribution' in (value as Record<string, any>))) || ((value as Record<string, any>)['readingStatusDistribution'] === undefined && (value as Record<string, any>)['reading_status_distribution'] === undefined)) return false;
    if ((!('overallStatusDistribution' in (value as Record<string, any>)) && !('overall_status_distribution' in (value as Record<string, any>))) || ((value as Record<string, any>)['overallStatusDistribution'] === undefined && (value as Record<string, any>)['overall_status_distribution'] === undefined)) return false;
    if ((!('categoryDistribution' in (value as Record<string, any>)) && !('category_distribution' in (value as Record<string, any>))) || ((value as Record<string, any>)['categoryDistribution'] === undefined && (value as Record<string, any>)['category_distribution'] === undefined)) return false;
    if ((!('ratingDistribution' in (value as Record<string, any>)) && !('rating_distribution' in (value as Record<string, any>))) || ((value as Record<string, any>)['ratingDistribution'] === undefined && (value as Record<string, any>)['rating_distribution'] === undefined)) return false;
    if ((!('topGenres' in (value as Record<string, any>)) && !('top_genres' in (value as Record<string, any>))) || ((value as Record<string, any>)['topGenres'] === undefined && (value as Record<string, any>)['top_genres'] === undefined)) return false;
    if ((!('topAuthors' in (value as Record<string, any>)) && !('top_authors' in (value as Record<string, any>))) || ((value as Record<string, any>)['topAuthors'] === undefined && (value as Record<string, any>)['top_authors'] === undefined)) return false;
    return true;
}

export function StatisticsFromJSON(json: any): Statistics {
    return StatisticsFromJSONTyped(json, false);
}

export function StatisticsFromJSONTyped(json: any, ignoreDiscriminator: boolean): Statistics {
    if (json == null) {
        return json;
    }
    return {

        'totalMangas': json['total_mangas'],
        'totalVolumes': json['total_volumes'],
        'totalAuthors': json['total_authors'],
        'totalGenres': json['total_genres'],
        'totalLists': json['total_lists'],
        'readingStatusDistribution': ((json['reading_status_distribution'] as Array<any>).map(StatisticCountFromJSON)),
        'overallStatusDistribution': ((json['overall_status_distribution'] as Array<any>).map(StatisticCountFromJSON)),
        'categoryDistribution': ((json['category_distribution'] as Array<any>).map(StatisticCountFromJSON)),
        'ratingDistribution': ((json['rating_distribution'] as Array<any>).map(StatisticCountFromJSON)),
        'topGenres': ((json['top_genres'] as Array<any>).map(StatisticCountFromJSON)),
        'topAuthors': ((json['top_authors'] as Array<any>).map(StatisticCountFromJSON)),
    };
}

export function StatisticsToJSON(json: any): Statistics {
    return StatisticsToJSONTyped(json, false);
}

export function StatisticsToJSONTyped(value?: Statistics | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'total_mangas': value['totalMangas'],
        'total_volumes': value['totalVolumes'],
        'total_authors': value['totalAuthors'],
        'total_genres': value['totalGenres'],
        'total_lists': value['totalLists'],
        'reading_status_distribution': ((value['readingStatusDistribution'] as Array<any>).map(StatisticCountToJSON)),
        'overall_status_distribution': ((value['overallStatusDistribution'] as Array<any>).map(StatisticCountToJSON)),
        'category_distribution': ((value['categoryDistribution'] as Array<any>).map(StatisticCountToJSON)),
        'rating_distribution': ((value['ratingDistribution'] as Array<any>).map(StatisticCountToJSON)),
        'top_genres': ((value['topGenres'] as Array<any>).map(StatisticCountToJSON)),
        'top_authors': ((value['topAuthors'] as Array<any>).map(StatisticCountToJSON)),
    };
}
