/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { StatisticCount } from './StatisticCount';
import {
    StatisticCountFromJSON,
    StatisticCountFromJSONTyped,
    StatisticCountToJSON,
    StatisticCountToJSONTyped,
} from './StatisticCount';

/**
 *
 * @export
 * @interface Statistics
 */
export interface Statistics {
    /**
     *
     * @type {number}
     * @memberof Statistics
     */
    totalMangas: number;
    /**
     *
     * @type {number}
     * @memberof Statistics
     */
    totalAuthors: number;
    /**
     *
     * @type {number}
     * @memberof Statistics
     */
    totalGenres: number;
    /**
     *
     * @type {number}
     * @memberof Statistics
     */
    totalLists: number;
    /**
     *
     * @type {Array<StatisticCount>}
     * @memberof Statistics
     */
    readingStatusDistribution: Array<StatisticCount>;
    /**
     *
     * @type {Array<StatisticCount>}
     * @memberof Statistics
     */
    overallStatusDistribution: Array<StatisticCount>;
    /**
     *
     * @type {Array<StatisticCount>}
     * @memberof Statistics
     */
    categoryDistribution: Array<StatisticCount>;
    /**
     *
     * @type {Array<StatisticCount>}
     * @memberof Statistics
     */
    ratingDistribution: Array<StatisticCount>;
    /**
     *
     * @type {Array<StatisticCount>}
     * @memberof Statistics
     */
    topGenres: Array<StatisticCount>;
    /**
     *
     * @type {Array<StatisticCount>}
     * @memberof Statistics
     */
    topAuthors: Array<StatisticCount>;
}

/**
 * Check if a given object implements the Statistics interface.
 */
export function instanceOfStatistics(value: object): value is Statistics {
    if (!('totalMangas' in value) || value['totalMangas'] === undefined) return false;
    if (!('totalAuthors' in value) || value['totalAuthors'] === undefined) return false;
    if (!('totalGenres' in value) || value['totalGenres'] === undefined) return false;
    if (!('totalLists' in value) || value['totalLists'] === undefined) return false;
    if (!('readingStatusDistribution' in value) || value['readingStatusDistribution'] === undefined) return false;
    if (!('overallStatusDistribution' in value) || value['overallStatusDistribution'] === undefined) return false;
    if (!('categoryDistribution' in value) || value['categoryDistribution'] === undefined) return false;
    if (!('ratingDistribution' in value) || value['ratingDistribution'] === undefined) return false;
    if (!('topGenres' in value) || value['topGenres'] === undefined) return false;
    if (!('topAuthors' in value) || value['topAuthors'] === undefined) return false;
    return true;
}

export function StatisticsFromJSON(json: any): Statistics {
    return StatisticsFromJSONTyped(json, false);
}

export function StatisticsFromJSONTyped(json: any, ignoreDiscriminator: boolean): Statistics {
    if (json == null) {
        return json;
    }
    return {

        'totalMangas': json['total_mangas'],
        'totalAuthors': json['total_authors'],
        'totalGenres': json['total_genres'],
        'totalLists': json['total_lists'],
        'readingStatusDistribution': ((json['reading_status_distribution'] as Array<any>).map(StatisticCountFromJSON)),
        'overallStatusDistribution': ((json['overall_status_distribution'] as Array<any>).map(StatisticCountFromJSON)),
        'categoryDistribution': ((json['category_distribution'] as Array<any>).map(StatisticCountFromJSON)),
        'ratingDistribution': ((json['rating_distribution'] as Array<any>).map(StatisticCountFromJSON)),
        'topGenres': ((json['top_genres'] as Array<any>).map(StatisticCountFromJSON)),
        'topAuthors': ((json['top_authors'] as Array<any>).map(StatisticCountFromJSON)),
    };
}

export function StatisticsToJSON(json: any): Statistics {
    return StatisticsToJSONTyped(json, false);
}

export function StatisticsToJSONTyped(value?: Statistics | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'total_mangas': value['totalMangas'],
        'total_authors': value['totalAuthors'],
        'total_genres': value['totalGenres'],
        'total_lists': value['totalLists'],
        'reading_status_distribution': ((value['readingStatusDistribution'] as Array<any>).map(StatisticCountToJSON)),
        'overall_status_distribution': ((value['overallStatusDistribution'] as Array<any>).map(StatisticCountToJSON)),
        'category_distribution': ((value['categoryDistribution'] as Array<any>).map(StatisticCountToJSON)),
        'rating_distribution': ((value['ratingDistribution'] as Array<any>).map(StatisticCountToJSON)),
        'top_genres': ((value['topGenres'] as Array<any>).map(StatisticCountToJSON)),
        'top_authors': ((value['topAuthors'] as Array<any>).map(StatisticCountToJSON)),
    };
}
