/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface StatisticCount
 */
export interface StatisticCount {
    /**
     *
     * @type {string}
     * @memberof StatisticCount
     */
    label: string;
    /**
     *
     * @type {number}
     * @memberof StatisticCount
     */
    count: number;
}

/**
 * Check if a given object implements the StatisticCount interface.
 */
export function instanceOfStatisticCount(value: object): value is StatisticCount {
    if (!('label' in value) || value['label'] === undefined) return false;
    if (!('count' in value) || value['count'] === undefined) return false;
    return true;
}

export function StatisticCountFromJSON(json: any): StatisticCount {
    return StatisticCountFromJSONTyped(json, false);
}

export function StatisticCountFromJSONTyped(json: any, ignoreDiscriminator: boolean): StatisticCount {
    if (json == null) {
        return json;
    }
    return {

        'label': json['label'],
        'count': json['count'],
    };
}

export function StatisticCountToJSON(json: any): StatisticCount {
    return StatisticCountToJSONTyped(json, false);
}

export function StatisticCountToJSONTyped(value?: StatisticCount | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'label': value['label'],
        'count': value['count'],
    };
}
