/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface UserUpdatePassword
 */
export interface UserUpdatePassword {
    /**
     *
     * @type {string}
     * @memberof UserUpdatePassword
     */
    username: string;
    /**
     *
     * @type {string}
     * @memberof UserUpdatePassword
     */
    password: string;
}

/**
 * Check if a given object implements the UserUpdatePassword interface.
 */
export function instanceOfUserUpdatePassword(value: object): value is UserUpdatePassword {
    if (!('username' in value) || value['username'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    return true;
}

export function UserUpdatePasswordFromJSON(json: any): UserUpdatePassword {
    return UserUpdatePasswordFromJSONTyped(json, false);
}

export function UserUpdatePasswordFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserUpdatePassword {
    if (json == null) {
        return json;
    }
    return {

        'username': json['username'],
        'password': json['password'],
    };
}

export function UserUpdatePasswordToJSON(json: any): UserUpdatePassword {
    return UserUpdatePasswordToJSONTyped(json, false);
}

export function UserUpdatePasswordToJSONTyped(value?: UserUpdatePassword | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'username': value['username'],
        'password': value['password'],
    };
}
