/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Volume
 */
export interface Volume {
    /**
     * 
     * @type {number}
     * @memberof Volume
     */
    id: number;
    /**
     * 
     * @type {number}
     * @memberof Volume
     */
    volumeNum: number;
    /**
     * 
     * @type {number}
     * @memberof Volume
     */
    mangaId: number;
    /**
     * 
     * @type {string}
     * @memberof Volume
     */
    coverImage: string;
}

/**
 * Check if a given object implements the Volume interface.
 */
export function instanceOfVolume(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "volumeNum" in value;
    isInstance = isInstance && "mangaId" in value;
    isInstance = isInstance && "coverImage" in value;

    return isInstance;
}

export function VolumeFromJSON(json: any): Volume {
    return VolumeFromJSONTyped(json, false);
}

export function VolumeFromJSONTyped(json: any, ignoreDiscriminator: boolean): Volume {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'volumeNum': json['volume_num'],
        'mangaId': json['manga_id'],
        'coverImage': json['cover_image'],
    };
}

export function VolumeToJSON(value?: Volume | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'volume_num': value.volumeNum,
        'manga_id': value.mangaId,
        'cover_image': value.coverImage,
    };
}

