/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface VolumeCreate
 */
export interface VolumeCreate {
    /**
     *
     * @type {string}
     * @memberof VolumeCreate
     */
    volumeNumber: string;
    /**
     *
     * @type {string}
     * @memberof VolumeCreate
     */
    coverImage?: string | null;
}

/**
 * Check if a given object implements the VolumeCreate interface.
 */
export function instanceOfVolumeCreate(value: object): value is VolumeCreate {
    if (!('volumeNumber' in value) || value['volumeNumber'] === undefined) return false;
    return true;
}

export function VolumeCreateFromJSON(json: any): VolumeCreate {
    return VolumeCreateFromJSONTyped(json, false);
}

export function VolumeCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): VolumeCreate {
    if (json == null) {
        return json;
    }
    return {

        'volumeNumber': json['volume_number'],
        'coverImage': json['cover_image'] == null ? undefined : json['cover_image'],
    };
}

export function VolumeCreateToJSON(json: any): VolumeCreate {
    return VolumeCreateToJSONTyped(json, false);
}

export function VolumeCreateToJSONTyped(value?: VolumeCreate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'volume_number': value['volumeNumber'],
        'cover_image': value['coverImage'],
    };
}
