/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  HTTPValidationError,
  MangaCreate,
  Source,
  SourceCreate,
} from '../models/index';
import {
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    MangaCreateFromJSON,
    MangaCreateToJSON,
    SourceFromJSON,
    SourceToJSON,
    SourceCreateFromJSON,
    SourceCreateToJSON,
} from '../models/index';

export interface CreateSourceApiV1SourcesCreatePostRequest {
    sourceCreate: SourceCreate;
}

export interface SearchMangaApiV1SourcesSearchPostRequest {
    title: string;
    sourceName: string;
}

/**
 *
 */
export class SourcesApi extends runtime.BaseAPI {

    /**
     * Create Source
     */
    async createSourceApiV1SourcesCreatePostRaw(requestParameters: CreateSourceApiV1SourcesCreatePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Source>> {
        if (requestParameters['sourceCreate'] == null) {
            throw new runtime.RequiredError(
                'sourceCreate',
                'Required parameter "sourceCreate" was null or undefined when calling createSourceApiV1SourcesCreatePost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/v1/sources/create`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SourceCreateToJSON(requestParameters['sourceCreate']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SourceFromJSON(jsonValue));
    }

    /**
     * Create Source
     */
    async createSourceApiV1SourcesCreatePost(requestParameters: CreateSourceApiV1SourcesCreatePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Source> {
        const response = await this.createSourceApiV1SourcesCreatePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get Sources
     */
    async getSourcesApiV1SourcesGetAllGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Source>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/sources/getAll`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(SourceFromJSON));
    }

    /**
     * Get Sources
     */
    async getSourcesApiV1SourcesGetAllGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Source>> {
        const response = await this.getSourcesApiV1SourcesGetAllGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Search Manga
     */
    async searchMangaApiV1SourcesSearchPostRaw(requestParameters: SearchMangaApiV1SourcesSearchPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<MangaCreate>>> {
        if (requestParameters['title'] == null) {
            throw new runtime.RequiredError(
                'title',
                'Required parameter "title" was null or undefined when calling searchMangaApiV1SourcesSearchPost().'
            );
        }

        if (requestParameters['sourceName'] == null) {
            throw new runtime.RequiredError(
                'sourceName',
                'Required parameter "sourceName" was null or undefined when calling searchMangaApiV1SourcesSearchPost().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['title'] != null) {
            queryParameters['title'] = requestParameters['title'];
        }

        if (requestParameters['sourceName'] != null) {
            queryParameters['source_name'] = requestParameters['sourceName'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/sources/search`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(MangaCreateFromJSON));
    }

    /**
     * Search Manga
     */
    async searchMangaApiV1SourcesSearchPost(requestParameters: SearchMangaApiV1SourcesSearchPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<MangaCreate>> {
        const response = await this.searchMangaApiV1SourcesSearchPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
