/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/manga/": {
    /** Get All Mangas */
    get: operations["get_all_mangas_manga__get"];
    /** Create Manga */
    post: operations["create_manga_manga__post"];
  };
  "/manga/id/{manga_id}": {
    /** Get Manga By Id */
    get: operations["get_manga_by_id_manga_id__manga_id__get"];
  };
  "/manga/title/{manga_title}": {
    /** Get Manga By Title */
    get: operations["get_manga_by_title_manga_title__manga_title__get"];
  };
  "/manga/genre/{genre_name}": {
    /** Get Mangas By Genres */
    get: operations["get_mangas_by_genres_manga_genre__genre_name__get"];
  };
  "/manga/author/{author_name}": {
    /** Get Mangas By Author */
    get: operations["get_mangas_by_author_manga_author__author_name__get"];
  };
  "/manga/id/add_vol/{manga_id}/{volume_num}": {
    /** Add Volume To Manga By Id */
    put: operations["add_volume_to_manga_by_id_manga_id_add_vol__manga_id___volume_num__put"];
  };
  "/manga/title/add_vol/{manga_title}/{volume_num}": {
    /** Add Volume To Manga By Title */
    put: operations["add_volume_to_manga_by_title_manga_title_add_vol__manga_title___volume_num__put"];
  };
  "/mal/{manga_title}": {
    /** Get Manga With Mal */
    get: operations["get_manga_with_mal_mal__manga_title__get"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    /** Author */
    Author: {
      /** Name */
      name: string;
      /** Role */
      role: string;
    };
    /** Genre */
    Genre: {
      /** Name */
      name: string;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** Manga */
    Manga: {
      /** Title */
      title: string;
      /** Description */
      description: string;
      /** Total Volumes */
      total_volumes: number;
      /** Volumes */
      volumes: number[];
      /** Authors */
      authors: components["schemas"]["Author"][];
      /** Genres */
      genres: components["schemas"]["Genre"][];
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type external = Record<string, never>;

export interface operations {
  /** Get All Mangas */
  get_all_mangas_manga__get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
    };
  };
  /** Create Manga */
  create_manga_manga__post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["Manga"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["Manga"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get Manga By Id */
  get_manga_by_id_manga_id__manga_id__get: {
    parameters: {
      path: {
        manga_id: number;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get Manga By Title */
  get_manga_by_title_manga_title__manga_title__get: {
    parameters: {
      path: {
        manga_title: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get Mangas By Genres */
  get_mangas_by_genres_manga_genre__genre_name__get: {
    parameters: {
      path: {
        genre_name: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get Mangas By Author */
  get_mangas_by_author_manga_author__author_name__get: {
    parameters: {
      path: {
        author_name: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Add Volume To Manga By Id */
  add_volume_to_manga_by_id_manga_id_add_vol__manga_id___volume_num__put: {
    parameters: {
      path: {
        manga_id: number;
        volume_num: number;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Add Volume To Manga By Title */
  add_volume_to_manga_by_title_manga_title_add_vol__manga_title___volume_num__put: {
    parameters: {
      path: {
        manga_title: string;
        volume_num: number;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get Manga With Mal */
  get_manga_with_mal_mal__manga_title__get: {
    parameters: {
      path: {
        manga_title: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["Manga"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
}
